image: haskell:8

stages:
  - build

build:
  stage: build
  script:
    - cabal update
    - cabal install --installdir public
  rules:
    - when: manual
  artifacts:
    paths:
      - public/hsc3-lisp
